# Site settings
title: Rich Bowman
email: RichardEBowman1@gmail.com
description: "Former Attorney Turned Web Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3d408b #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/TheBostonREB
  - title: github
    url: http://github.com/BostonREB
  - title: linkedin
    url: http://linkedin.com/in/bostonreb

# Postal address (add as many lines as necessary)
address:
  - line: 63 Brainerd Road
  - line: Boston, MA 02134

# Build settings
markdown: kramdown
permalink: pretty
